//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.10 at 01:24:45 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:trimet:schedule", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.nimbler.tp.dataobject.trimet.schedule;
