//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.16 at 02:47:42 PM IST 
//


package com.nimbler.tp.dataobject.trimet.arrivals;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.nimbler.tp.dataobject.trimet.arrivals package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ResultSet_QNAME = new QName("urn:trimet:arrivals", "resultSet");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.nimbler.tp.dataobject.trimet.arrivals
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link LayoverType }
     * 
     */
    public LayoverType createLayoverType() {
        return new LayoverType();
    }

    /**
     * Create an instance of {@link ArrivalType }
     * 
     */
    public ArrivalType createArrivalType() {
        return new ArrivalType();
    }

    /**
     * Create an instance of {@link LocationType }
     * 
     */
    public LocationType createLocationType() {
        return new LocationType();
    }

    /**
     * Create an instance of {@link ResultSet }
     * 
     */
    public ResultSet createResultSet() {
        return new ResultSet();
    }

    /**
     * Create an instance of {@link BlockPositionType }
     * 
     */
    public BlockPositionType createBlockPositionType() {
        return new BlockPositionType();
    }

    /**
     * Create an instance of {@link TripType }
     * 
     */
    public TripType createTripType() {
        return new TripType();
    }

    /**
     * Create an instance of {@link RouteStatusType }
     * 
     */
    public RouteStatusType createRouteStatusType() {
        return new RouteStatusType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResultSet }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:trimet:arrivals", name = "resultSet")
    public JAXBElement<ResultSet> createResultSet(ResultSet value) {
        return new JAXBElement<ResultSet>(_ResultSet_QNAME, ResultSet.class, null, value);
    }

}
