//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.16 at 02:47:42 PM IST 
//


package com.nimbler.tp.dataobject.trimet.arrivals;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tripType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tripType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="progress" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="destDist" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="route" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="dir" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="tripNum" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="pattern" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="desc" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tripType")
public class TripType {

    @XmlAttribute(required = true)
    protected int progress;
    @XmlAttribute(required = true)
    protected int destDist;
    @XmlAttribute(required = true)
    protected int route;
    @XmlAttribute(required = true)
    protected int dir;
    @XmlAttribute(required = true)
    protected int tripNum;
    @XmlAttribute(required = true)
    protected int pattern;
    @XmlAttribute(required = true)
    protected String desc;

    /**
     * Gets the value of the progress property.
     * 
     */
    public int getProgress() {
        return progress;
    }

    /**
     * Sets the value of the progress property.
     * 
     */
    public void setProgress(int value) {
        this.progress = value;
    }

    /**
     * Gets the value of the destDist property.
     * 
     */
    public int getDestDist() {
        return destDist;
    }

    /**
     * Sets the value of the destDist property.
     * 
     */
    public void setDestDist(int value) {
        this.destDist = value;
    }

    /**
     * Gets the value of the route property.
     * 
     */
    public int getRoute() {
        return route;
    }

    /**
     * Sets the value of the route property.
     * 
     */
    public void setRoute(int value) {
        this.route = value;
    }

    /**
     * Gets the value of the dir property.
     * 
     */
    public int getDir() {
        return dir;
    }

    /**
     * Sets the value of the dir property.
     * 
     */
    public void setDir(int value) {
        this.dir = value;
    }

    /**
     * Gets the value of the tripNum property.
     * 
     */
    public int getTripNum() {
        return tripNum;
    }

    /**
     * Sets the value of the tripNum property.
     * 
     */
    public void setTripNum(int value) {
        this.tripNum = value;
    }

    /**
     * Gets the value of the pattern property.
     * 
     */
    public int getPattern() {
        return pattern;
    }

    /**
     * Sets the value of the pattern property.
     * 
     */
    public void setPattern(int value) {
        this.pattern = value;
    }

    /**
     * Gets the value of the desc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDesc() {
        return desc;
    }

    /**
     * Sets the value of the desc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDesc(String value) {
        this.desc = value;
    }

}
